document.writeln('<script async src="\/\/pagead2.googlesyndication.com\/pagead\/js\/adsbygoogle.js"><\/script>');
document.writeln('<script>');
document.writeln('  (adsbygoogle = window.adsbygoogle || []).push({');
document.writeln('    google_ad_client: "ca-pub-6857274579996319",');
document.writeln('    enable_page_level_ads: true');
document.writeln('  });');
document.writeln('<\/script>');
document.writeln('<script>');
document.writeln('var _hmt = _hmt || [];');
document.writeln('(function() {');
document.writeln('  var hm = document.createElement("script");');
document.writeln('  hm.src = "https:\/\/hm.baidu.com\/hm.js?9b38452641b19b86b07bcb32fbbd0f98";');
document.writeln('  var s = document.getElementsByTagName("script")[0]; ');
document.writeln('  s.parentNode.insertBefore(hm, s);');
document.writeln('})();');
document.writeln('<\/script>');
